const fs = require('fs');
const path = require('path');

// Supported MCU targets and their default pin mapping.
// ESP32: classic DevKit (V1) wiring. ESP8266: NodeMCU classic MFRC522 wiring.
const TARGETS = {
  esp32: {
    platform: 'espressif32',
    board: 'esp32dev',
    label: 'ESP32',
    wifiInclude: '#include <WiFi.h>',
    pins: { ss: 5, rst: 27, buzzer: 4 },
    wiring: [
      '  SDA (SS)  ->  GPIO 5',
      '  SCK       ->  GPIO 18',
      '  MOSI      ->  GPIO 23',
      '  MISO      ->  GPIO 19',
      '  IRQ       ->  not connected',
      '  GND       ->  GND',
      '  RST       ->  GPIO 27',
      '  3.3V      ->  3.3V'
    ]
  },
  esp8266: {
    platform: 'espressif8266',
    board: 'nodemcuv2',
    label: 'ESP8266 NodeMCU',
    wifiInclude: '#include <ESP8266WiFi.h>',
    pins: { ss: 15, rst: 0, buzzer: 2 },
    wiring: [
      '  SDA (SS)  ->  D8 (GPIO15)',
      '  SCK       ->  D5 (GPIO14)',
      '  MOSI      ->  D7 (GPIO13)',
      '  MISO      ->  D6 (GPIO12)',
      '  IRQ       ->  not connected',
      '  GND       ->  GND',
      '  RST       ->  D3 (GPIO0)',
      '  3.3V      ->  3.3V'
    ]
  }
};

const DEFAULT_PINS = TARGETS.esp32.pins;

function esc(value) {
  return String(value == null ? '' : value)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"');
}

function escUid(value) {
  return String(value == null ? '' : value).replace(/[^a-zA-Z0-9:_-]/g, '');
}

function targetFor(config = {}) {
  return TARGETS[config.mcu] || TARGETS.esp32;
}

function generateIno(config = {}) {
  const target = targetFor(config);
  const ssid = config.ssid || 'YOUR_WIFI_NAME';
  const password = config.password || '';
  const serverUrl = config.serverUrl || 'http://192.168.1.100:3001/api/scan';
  const readerId = config.readerId || 'reader-01';
  const pins = Object.assign({}, target.pins, config.pins || {});

  return `/*
 * Arcade Tournament Manager - ${target.label} RFID Reader
 * =======================================================
 * Auto-generated by the Arcade Tournament Manager Setup screen.
 * Reads RFID badges and reports scans to the AT Manager app.
 *
 * WIRING (MFRC522 -> ${target.label}):
${target.wiring.join('\n')}
 *
 * OPTIONAL ACTIVE BUZZER (1s beep on successful check-in):
 *   Positive (+)  ->  GPIO ${pins.buzzer}
 *   Negative (-)  ->  GND
 * ========================================================
 */

${target.wifiInclude}
#include <HTTPClient.h>
#include <SPI.h>
#include <MFRC522.h>

// ====== CONFIGURE THESE FOR EACH READER ======
const char* WIFI_SSID      = "${esc(ssid)}";
const char* WIFI_PASSWORD  = "${esc(password)}";
const char* SERVER_URL     = "${esc(serverUrl)}";
const char* READER_ID      = "${escUid(readerId)}";  // Unique per reader!

#define SS_PIN       ${pins.ss}
#define RST_PIN      ${pins.rst}
#define BUZZER_PIN   ${pins.buzzer}

MFRC522 rfid(SS_PIN, RST_PIN);
String lastUID = "";
unsigned long lastScanTime = 0;
const unsigned long DEBOUNCE_MS = 3000;  // Ignore same badge for 3 seconds

// Beep for 1 second on a successful check-in
void successBeep() {
  digitalWrite(BUZZER_PIN, HIGH);   // active buzzer = beep on
  delay(1000);
  digitalWrite(BUZZER_PIN, LOW);    // beep off
}

void setup() {
  Serial.begin(115200);
  pinMode(BUZZER_PIN, OUTPUT);
  digitalWrite(BUZZER_PIN, LOW);

  SPI.begin();
  rfid.PCD_Init();
  delay(100);

  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.print("Connecting to WiFi");
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("\\nConnected! IP: " + WiFi.localIP().toString());
  Serial.println("Ready to scan badges...");
}

void loop() {
  if (WiFi.status() != WL_CONNECTED) {
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
    delay(5000);
    return;
  }

  if (!rfid.PICC_IsNewCardPresent() || !rfid.PICC_ReadCardSerial()) {
    return;
  }

  String uid = "";
  for (byte i = 0; i < rfid.uid.size; i++) {
    if (rfid.uid.uidByte[i] < 0x10) uid += "0";
    uid += String(rfid.uid.uidByte[i], HEX);
    if (i < rfid.uid.size - 1) uid += ":";
  }
  uid.toUpperCase();

  rfid.PICC_HaltA();
  rfid.PCD_StopCrypto1();

  if (uid == lastUID && millis() - lastScanTime < DEBOUNCE_MS) {
    return;
  }

  lastUID = uid;
  lastScanTime = millis();
  Serial.println("Badge scanned: " + uid);
  sendScan(uid);
}

void sendScan(String uid) {
  HTTPClient http;
  http.begin(SERVER_URL);
  http.addHeader("Content-Type", "application/json");

  String payload = "{\\"badge_uid\\":\\"" + uid
    + "\\",\\"reader_id\\":\\"" + READER_ID + "\\"}";

  int httpCode = http.POST(payload);

  if (httpCode > 0) {
    String response = http.getString();
    Serial.println("Response: " + response);

    // Beep for 1 second only on a successful check-in
    if (response.indexOf("checked_in") != -1) {
      successBeep();
    }
  } else {
    Serial.println("FAILED: " + http.errorToString(httpCode));
  }
  http.end();
}
`;
}

function platformioIni(config = {}) {
  const target = targetFor(config);
  return `; Arcade Tournament Manager - ${target.label} RFID Reader
; Auto-generated PlatformIO configuration

[env:${target.board}]
platform = ${target.platform}
board = ${target.board}
framework = arduino
monitor_speed = 115200
lib_deps =
    miguelbalboa/MFRC522@^1.4.10
`;
}

// Write firmware source + platformio.ini into a fresh workspace dir.
// PlatformIO looks for source in a `src/` subfolder.
function writeWorkspace(dir, config = {}) {
  fs.mkdirSync(dir, { recursive: true });
  const srcDir = path.join(dir, 'src');
  fs.mkdirSync(srcDir, { recursive: true });
  const inoPath = path.join(srcDir, 'arcade_rfid_reader.ino');
  fs.writeFileSync(inoPath, generateIno(config));
  fs.writeFileSync(path.join(dir, 'platformio.ini'), platformioIni(config));
  return { dir, inoPath };
}

module.exports = { generateIno, platformioIni, PLATFORMIO_INI: platformioIni(), writeWorkspace, DEFAULT_PINS, TARGETS };
